import { Inter } from 'next/font/google'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Prueba Tecnica MELI',
	description: 'Generated by create next app, developed by Guido',
}

const RootLayout = ({ children }) => {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	)
}

export default RootLayout
